input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][index]" => "msa-prc-%{service}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index]" => "msa-prc-unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
}
