# helm install postgres-auth bitnami/postgresql -n msa -f k8s/infra/postgres-auth-values.yaml
auth:
  username: admin
  password: "CHANGE_ME"
  database: authorization_db

primary:
  persistence:
    size: 2Gi

readReplicas:
  replicaCount: 0
