global:
  scrape_interval: 15s

scrape_configs:
  - job_name: authorization-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:1010' ]

  - job_name: jwt-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:1020' ]

  - job_name: opaque-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:1030' ]

  - job_name: gateway-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:1100' ]

  - job_name: config-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:1110' ]

  - job_name: eureka-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:1120' ]
