spring:
  datasource:
    url: jdbc:postgresql://postgres-jwt:5432/jwt_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: redis-master  # Bitnami Redis Helm chart의 master 서비스명
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092

  elasticsearch:
    uris: http://elasticsearch:9200

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/ddl/authorization_users.sql
        - classpath:sql/ddl/authorization_system_clients.sql
        - classpath:sql/ddl/posts.sql
        - classpath:sql/ddl/comments.sql
        - classpath:sql/ddl/likes.sql
        - classpath:sql/ddl/follows.sql
        - classpath:sql/ddl/hashtags.sql
        - classpath:sql/ddl/reports.sql
        - classpath:sql/ddl/outbox_events.sql
        - classpath:sql/ddl/processed_kafka_events.sql

minio:
  endpoint: http://minio:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  logstash:
    host: logstash
    port: 5000
  level:
    root: INFO
    com.example: INFO
