spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/opaque_db
    username: admin
    password: admin
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: DEBUG
    com.example: DEBUG
